import "bootstrap/dist/css/bootstrap.min.css";
import { Abril_Fatface, Oswald } from "next/font/google";
import "./globals.css";
import "@/components/navbar/Navbar";
import Navbar from "@/components/navbar/Navbar";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

export const metadata = {
  title: "Speak-Journey",
  description: "Generated by create next app",
};

export const abrila = Abril_Fatface({
  weight: ["400"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-abrila",
});
export const oswald = Oswald({
  weight: ["400", "500"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-oswald",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${abrila.variable} ${oswald.variable}`}>
        <ToastContainer />
        <Navbar />
        {children}
      </body>
    </html>
  );
}
